databases:
  - name: mydb
    plan: free
    databaseName: mydb
    user: mydbuser

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
