# Generated by Django 5.0.3 on 2024-03-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_myt_10'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myt_10',
            name='description_text_of_t10',
        ),
        migrations.AddField(
            model_name='myt_10',
            name='rank',
            field=models.FloatField(default=0.0),
        ),
    ]
