# Generated by Django 5.0.3 on 2024-03-15 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_myt_10_id_alter_myt_10_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='myt_10',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myt_10',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.filmcard'),
        ),
        migrations.AlterField(
            model_name='myt_10',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
