# Generated by Django 5.0.3 on 2024-03-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_myt_10_id_alter_myt_10_film_alter_myt_10_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myt_10',
            name='rank',
            field=models.FloatField(default=0),
        ),
    ]
