# Generated by Django 5.0.3 on 2024-03-15 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_myt_10_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myt_10',
            name='film',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.filmcard'),
        ),
    ]
