# Generated by Django 5.0.3 on 2024-03-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_myt_10_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myt_10',
            options={},
        ),
    ]
