# Generated by Django 5.0.3 on 2024-03-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_filmcard_author_alter_myt_10_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmcard',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
