# Generated by Django 5.0.3 on 2024-03-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_filmcard_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myt_10',
            name='rank',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
