# Generated by Django 5.0.3 on 2024-03-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='is_liked',
            field=models.BooleanField(default=True),
        ),
    ]
