# Generated by Django 5.0.3 on 2024-03-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_post_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_liked',
        ),
    ]
