# Generated by Django 5.0.3 on 2024-03-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_comment_post_alter_likes_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_liked',
        ),
    ]
